# Generated by Django 3.2.11 on 2022-08-01 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields
import mptt.fields
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_alter_product_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='カテゴリー名（日本語）')),
                ('title_en', models.CharField(db_index=True, max_length=255, verbose_name='カテゴリー（英語）')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hero', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/heros/')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='recipes.category')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.SlugField(default=recipes.models.unique_rand, max_length=8, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('serves', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=True)),
                ('hero', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='photos/heros/')),
                ('caution', models.TextField(blank=True, null=True)),
                ('freespace_a', models.TextField(blank=True, null=True)),
                ('freespace_b', models.TextField(blank=True, null=True)),
                ('freespace_c', models.TextField(blank=True, null=True)),
                ('freespace_d', models.TextField(blank=True, null=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category', models.ManyToManyField(blank=True, related_name='recipe', to='recipes.Category')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', model_utils.fields.StatusField(choices=[('tag', 'ノーマルタグ'), ('menu', 'メニュータイプ'), ('dish', 'ディッシュタイプ'), ('event', 'イベント')], default='tag', max_length=100, no_check_for_status=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(max_length=255)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.nutrient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrients',
            field=models.ManyToManyField(blank=True, related_name='recipe', through='recipes.RecipeNutrient', to='recipes.Nutrient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='recipe', through='recipes.RecipeProduct', to='products.Product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='recipe_relative', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.series'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_recipe',
            field=models.ManyToManyField(blank=True, related_name='recipe_owner', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='recipe', to='recipes.Tag'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos')),
                ('label', model_utils.fields.StatusField(choices=[('main', 'main'), ('cooked', 'cooked'), ('package', 'package')], default='main', max_length=100, no_check_for_status=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField(blank=True, null=True)),
                ('label', model_utils.fields.StatusField(choices=[('step', 'ステップ'), ('title', 'タイトル')], default='step', max_length=100, no_check_for_status=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.recipe')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
    ]
