# Generated by Django 3.2.11 on 2022-07-31 01:02

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='label',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='step', max_length=100, no_check_for_status=True),
        ),
    ]
