# Generated by Django 3.2.11 on 2022-08-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recommendeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='show_in_list',
            field=models.BooleanField(default=True),
        ),
    ]
