# Generated by Django 3.2.11 on 2022-03-16 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='カテゴリー')),
                ('description', models.TextField(blank=True, null=True)),
                ('hero', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/heros/')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hero', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/heros/')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('shipping_date', models.DateTimeField(blank=True)),
                ('hero', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/heros/')),
                ('preservation', model_utils.fields.StatusField(choices=[('room_temp', '常温'), ('frozen', '冷凍')], default='room_temp', help_text='温度帯', max_length=100, no_check_for_status=True)),
                ('category', models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Category')),
                ('facility', models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Facility')),
                ('industry', models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Tag'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos')),
                ('label', model_utils.fields.StatusField(choices=[('main', 'main'), ('cooked', 'cooked'), ('package', 'package')], default='cooked', max_length=100, no_check_for_status=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Handling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('recipe', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.series')),
            ],
        ),
    ]
