# Generated by Django 3.2.11 on 2022-03-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220317_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
