# Generated by Django 3.2.11 on 2022-03-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220320_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Packing',
            new_name='packing',
        ),
    ]
