# Generated by Django 3.2.11 on 2022-03-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_packing_product_packing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='series',
            new_name='brand',
        ),
    ]
