# Generated by Django 3.2.11 on 2022-03-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_shipping_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_date',
        ),
    ]
