# Generated by Django 3.2.11 on 2022-03-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_series_series_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='freespace_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='freespace_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='freespace_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='handling_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='handling_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
