# Generated by Django 3.2.11 on 2022-03-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220317_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='product',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
