# Generated by Django 3.2.11 on 2022-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220317_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='facility',
            field=models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Facility'),
        ),
        migrations.AddField(
            model_name='product',
            name='industry',
            field=models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Industry'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, default=False, related_name='product', to='products.Tag'),
        ),
    ]
