# Generated by Django 3.2.11 on 2022-03-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220321_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preservation',
        ),
    ]
