# Generated by Django 3.2.11 on 2022-03-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220325_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
